"""add audit_events, users, device_keys

Revision ID: 02234c7da915
Revises: 
Create Date: 2026-09-16 16:50:38.126950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02234c7da915'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('platform_user_id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("platform IN ('slack', 'teams')", name='ck_users_platform'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_user_id', name='uq_users_platform_user')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload_id_prefix', sa.String(length=8), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('created', 'revealed', 'expired', 'denied')", name='ck_audit_events_event_type'),
    sa.CheckConstraint('payload_id_prefix IS NULL OR length(payload_id_prefix) <= 8', name='ck_audit_events_prefix_length'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_created_at', 'audit_events', ['created_at'], unique=False)
    op.create_index('ix_audit_events_payload_id_prefix', 'audit_events', ['payload_id_prefix'], unique=False)
    op.create_table('device_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_device_keys_user_id', 'device_keys', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Audit rows are append-only. A GRANT/REVOKE is not sufficient here: the API
    # currently connects as the table owner, and an owner cannot revoke its own
    # implicit rights. A trigger binds the owner too, so tampering fails loudly
    # instead of silently succeeding.
    #
    # Residual gap: a superuser can still ALTER TABLE ... DISABLE TRIGGER or drop
    # the trigger outright. Closing that requires running the API as a dedicated
    # non-owner, non-superuser role. Tracked in docs/security/security-controls.md.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION audit_events_append_only()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION 'audit_events is append-only: % is not permitted', TG_OP;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_audit_events_append_only
        BEFORE UPDATE OR DELETE ON audit_events
        FOR EACH ROW EXECUTE FUNCTION audit_events_append_only()
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_audit_events_append_only ON audit_events")
    op.execute("DROP FUNCTION IF EXISTS audit_events_append_only()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_keys_user_id', table_name='device_keys')
    op.drop_table('device_keys')
    op.drop_index('ix_audit_events_payload_id_prefix', table_name='audit_events')
    op.drop_index('ix_audit_events_created_at', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('users')
    # ### end Alembic commands ###
